openapi: 3.2.0
info:
  version: 2.0.0
  title: Anchorage Digital API Reference Statements API
  contact:
    email: api@anchorage.com
  description: '# Introduction

    *CONFIDENTIAL: Please do not distribute this documentation externally without prior Anchorage Digital approval.*


    The Anchorage Digital REST API v2.0 provides a set of operations and resources that allow Anchorage Digital clients and partners to:

    - Programmatically transfer funds from an Anchorage Digital vault or wallet without human intervention

    - Create and list deposit addresses in a vault

    - Read and monitor vault balances

    - Query transaction history including deposits

    …'
servers:
- url: https://api.anchorage-staging.com/v2
security:
- Api-Access-Key: []
tags:
- description: ''
  name: Statements
paths:
  /statement-types:
    get:
      operationId: listStatementTypes
      summary: List statement types
      description: 'Permissions required: **Read Statement**


        List the available statement types.'
      parameters:
      - name: afterId
        in: query
        description: When paginating this is used to provide the starting point for the page to fetch (retrieved from the previous response body)
        schema:
          type: string
      - name: limit
        in: query
        description: Maximum number of results to return per query
        schema:
          type: integer
          format: int64
          default: 25
          maximum: 100
          minimum: 1
      responses:
        '200':
          description: Statement Type list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/StatementType'
                  page:
                    $ref: '#/components/schemas/Page'
                required:
                - data
                - page
              example:
                data:
                - id: b00e2483-57a1-4db4-8ea1-b91223a76a20
                  name: Brokerage Monthly Statement
                - id: d3b07384-d9a0-4f8b-8a1a-6f3e4b2e4f8b
                  name: Custody Monthly Statement
                - id: 058da362-31a7-4e2b-ae3e-77b095389a5f
                  name: Exchange Trade Fund
                - id: e6ffd062-7bbc-4d72-b9d0-409f7fe7dd0d
                  name: Program Customer Monthly
                - id: cbe88de1-2470-46f1-aa59-932eeda16ba2
                  name: Registered Investment Advisor
                page:
                  next: null
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - Statements
  /statements:
    get:
      operationId: listStatements
      summary: List statements
      description: 'Permissions required: **Read Statement**


        List the available statements.'
      parameters:
      - name: afterId
        in: query
        description: When paginating this is used to provide the starting point for the page to fetch (retrieved from the previous response body)
        schema:
          type: string
      - name: limit
        in: query
        description: Maximum number of results to return per query
        schema:
          type: integer
          format: int64
          default: 25
          maximum: 100
          minimum: 1
      - name: ids
        in: query
        schema:
          type: array
          items:
            type: string
            format: uuid
        example:
        - 3486b413-93d3-4447-afce-2b9c9dc34a32
        - 8de0fc33-7443-4dcf-bbf1-4ca8d0e0509f
      - name: typeIds
        in: query
        schema:
          type: array
          items:
            type: string
        example:
        - 058da362-31a7-4e2b-ae3e-77b095389a5f
        - b00e2483-57a1-4db4-8ea1-b91223a76a20
      - name: customerIds
        in: query
        schema:
          type: array
          items:
            type: string
        example:
        - 1ac10949bbbf483e8df3c0f8ef97146bc9ce6f5890df40fa8777ea63dc932f7b
        - fbcdb420fca4439d919089e60d59cd5b12b692d215694681b636bffb6cb1618c
      - name: createdAfter
        in: query
        schema:
          type: string
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        example: '2025-01-01T00:00:00.000Z'
      - name: createdBefore
        in: query
        schema:
          type: string
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        example: '2025-12-31T23:59:59.999Z'
      - name: correctedAfter
        in: query
        description: Filter for statements corrected at or after this time
        schema:
          type: string
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        example: '2025-01-01T00:00:00.000Z'
      - name: correctedBefore
        in: query
        description: Filter for statements corrected at or before this time
        schema:
          type: string
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        example: '2025-12-31T23:59:59.999Z'
      responses:
        '200':
          description: Statement list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Statement'
                  page:
                    $ref: '#/components/schemas/Page'
                required:
                - data
                - page
              example:
                data:
                - customerId: fbcdb420fca4439d919089e60d59cd5b12b692d215694681b636bffb6cb1618c
                  createdAt: '2025-03-27T17:15:42.793685Z'
                  displayName: ETF Statement October 2025
                  id: 8de0fc33-7443-4dcf-bbf1-4ca8d0e0509f
                  typeId: 058da362-31a7-4e2b-ae3e-77b095389a5f
                - customerId: fbcdb420fca4439d919089e60d59cd5b12b692d215694681b636bffb6cb1618c
                  createdAt: '2025-04-01T00:15:00.738904Z'
                  displayName: ETF Statement December 2025
                  id: db3021e7-b2c4-4b80-8d9c-b754f1b4ef5f
                  typeId: 058da362-31a7-4e2b-ae3e-77b095389a5f
                - customerId: fbcdb420fca4439d919089e60d59cd5b12b692d215694681b636bffb6cb1618c
                  createdAt: '2025-09-01T00:47:16.937934Z'
                  displayName: ETF Statement September 2025
                  id: a7f61ad0-89fe-4e9d-9285-7219d7c51c6b
                  typeId: 058da362-31a7-4e2b-ae3e-77b095389a5f
                page:
                  next: null
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - Statements
  /statements/{statementId}:
    get:
      operationId: getStatement
      summary: Get statement
      description: 'Permissions required: **Read Statement**


        Get the details for a statement.'
      parameters:
      - name: statementId
        in: path
        description: Unique identifier for the statement
        required: true
        schema:
          type: string
          format: uuid
        example: 3486b413-93d3-4447-afce-2b9c9dc34a32
      responses:
        '200':
          description: Statement Details
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/StatementDetails'
                required:
                - data
              example:
                data:
                  customerId: 3ed6ef079913cb5e786c03f73326511b0bbebc438f941cb13650d48650904fc6
                  createdAt: '2025-09-01T00:47:16.937934Z'
                  displayName: RIA Statement September 2025
                  id: 2cfb5ca8-8a71-11f0-969e-42010a1f04ea
                  typeId: 058da362-31a7-4e2b-ae3e-77b095389a5f
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - Statements
  /statements/{statementId}/download:
    get:
      operationId: downloadStatement
      summary: Download a statement
      description: 'Permissions required: **Read Statement**


        Download a statement as a PDF file.


        This endpoint streams the PDF file directly. The response body contains the binary content of the PDF file.'
      parameters:
      - name: statementId
        in: path
        description: Unique identifier for the statement
        required: true
        schema:
          type: string
          format: uuid
        example: 3486b413-93d3-4447-afce-2b9c9dc34a32
      responses:
        '200':
          description: Statement PDF file streamed as binary content
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
      tags:
      - Statements
components:
  schemas:
    StatementType:
      type: object
      properties:
        id:
          type: string
          example: b00e2483-57a1-4db4-8ea1-b91223a76a20
        name:
          type: string
          example: Brokerage Monthly Statement
      required:
      - id
      - name
    Statement:
      type: object
      properties:
        correctedAt:
          description: The time the statement was corrected. This field may be omitted if the statement has not been corrected
          type:
          - string
          - 'null'
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        createdAt:
          type: string
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        customerId:
          type: string
          example: 1ac10949bbbf483e8df3c0f8ef97146bc9ce6f5890df40fa8777ea63dc932f7b
        displayName:
          type: string
          example: September 2025 Statement
        id:
          type: string
          example: 3486b413-93d3-4447-afce-2b9c9dc34a32
        typeId:
          type: string
          example: 058da362-31a7-4e2b-ae3e-77b095389a5f
      required:
      - id
      - typeId
      - createdAt
      - displayName
    StatementDetails:
      type: object
      properties:
        correctedAt:
          description: The time the statement was corrected. This field may be omitted if the statement has not been corrected
          type:
          - string
          - 'null'
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        createdAt:
          type: string
          format: date-time
          example: '2019-01-02T12:34:56.000Z'
        customerId:
          type: string
          example: 1ac10949bbbf483e8df3c0f8ef97146bc9ce6f5890df40fa8777ea63dc932f7b
        displayName:
          type: string
          example: September 2025 Statement
        id:
          type: string
          example: 8de0fc33-7443-4dcf-bbf1-4ca8d0e0509f
        typeId:
          type: string
          example: 058da362-31a7-4e2b-ae3e-77b095389a5f
      required:
      - id
      - typeId
      - createdAt
      - displayName
    Page:
      description: Pagination info
      type: object
      properties:
        next:
          description: URL to use to query for the next page or null if no additional results are available
          type:
          - string
          - 'null'
          example: <next page url>
          x-omitempty: false
      title: Page
    ErrorType:
      description: The type of error returned.
      type: string
      enum:
      - InternalError
      - InvalidRequest
      - Unauthenticated
      - Forbidden
      - NotFound
      - Conflict
      - UnprocessableEntity
      - TooManyRequests
      - ServiceUnavailable
      - QuoteExpired
      - InsufficientFunds
      - NotImplemented
      title: ErrorType
    ErrorDetails:
      type: object
      properties:
        errorType:
          $ref: '#/components/schemas/ErrorType'
        message:
          description: A human-readable message providing more details about the error.
          type: string
          example: Missing required field 'amount'.
      required:
      - errorType
      - message
      title: ErrorDetails
  securitySchemes:
    Api-Access-Key:
      type: apiKey
      name: Api-Access-Key
      in: header
      description: An API key associated with a security role
x-tagGroups:
- name: Under Development
  tags:
  - Collateral Management
  - Holds
  - Deposit Attribution
  - Onboarding
  - Trusted Destinations
  - Atlas Settlement Network
  - Tax
- name: API Endpoints
  tags:
  - Addresses
  - Asset Types
  - Transactions
  - Transfers
  - Wallets
  - Vaults
  - Vesting
  - Tagging
  - Subaccounts
  - Stablecoins
  - Webhook Notifications
  - API Key
  - Statements
  - Tax Reporting
  - Trading
- name: Models
  tags:
  - Transfer Model
  - Transaction Model
  - Vault Model
  - Deposit Attribution Model
